sudo: required
services:
  - docker
language: bash
script:
  - make rpi-raw-image
  - make odroid-raw-image
  - ls -lah
branches:
  only:
    - master
    - /^v\d.*$/
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: yTibEbfHljEK52KfRXJBXIG3g9zuA87YZTD9rBb23sVENqySIccWdo7oI7bKY7BBS8t2Xu8pEJlp0MkD/DmsF3Bv04zMzx9hfAl0uUDSpAlucb4feI1qy0Sr8B+Td1e7tUC0QvAvJzt3fqhfAot3tao1Q1aBg0zpo8kn7WOG0HA09d2C9n+jLNeRGaU1/P4hJB9ToRD/zr9/9ox/LoOPj14EzMidzUqLgDIEwPaHfNZPBCO0oEwM1h4KDfopkIok02fCpGli/eITUVZT21RGvlLPmiKhJ+Vhrp07bkeQ0OCV7KF9Wt4NBrF1xGvvN/ha9B6MPpH9+jzUZrlbAT1yVFFax2z/ef18iyyBUI5WtSREwSKL8ITfb0yaSBgweXuSRuQWyVw0vSpiBCsN0o1mSPHSQeiQgbKvXa2Mxh7IRCKk+nIWqfZ9f2/kayHBy1QVIQNJLouSyU4f41ali2xkniG2m91xAZUPnQ5K1kWgU0h30VUvBsy5l9HWVpd21QB9WKHRkdi0UsekXqplbLO2OWC1lKBYu5bZtchcQ9Kz5+s5cMdetwss8B5dWJ69RGWUPRqtR53HuvQIM6sjAjZwToD+YevMw82eXVTi1XZPmSQhw7Ah0Xl6igrMNzetHs4A6Zf02XSv9jgohECcgTib2BbXx0ifSplNAmeFVY7Qgo8=
  file:
    - "rpi-raw-k8s.img.zip"
    - "rpi-raw-k8s.img.zip.sha256"
    - "odroid-raw-k8s.img.zip"
    - "odroid-raw-k8s.img.zip.sha256"
  on:
    tags: true
    repo: Tombar/image-builder-raw-k8s
